export const EVENTS_MAP = {
  BILL_CREATED: "BILL_CREATED",
  BILL_CREATION_NOTIFICATION: "BILL_CREATION_NOTIFICATION",
  TRANSACTION_CREATED: "TRANSACTION_CREATED",
  TRANSACTION_CREATION_NOTIFICATION: "TRANSACTION_CREATION_NOTIFICATION",
};
