export const EVENTS_MAP = {
  BILL_CREATED: "BILL_CREATED",
  BILL_CREATION_NOTIFICATION: "BILL_CREATION_NOTIFICATION",
  TRANSACTION_CREATED: "TRANSACTION_CREATED",
  TRANSACTION_APPROVED: "TRANSACTION_APPROVED",
  TRANSACTION_CREATION_NOTIFICATION: "TRANSACTION_CREATION_NOTIFICATION",
  STOCK_REQUEST_RAISED_NOTIFICATION: "STOCK_REQUEST_RAISED_NOTIFICATION",
  STOCK_UPDATED: "STOCK_UPDATED",
  PRODUCT_CREATED: "PRODUCT_CREATED",
  PRODUCT_UPDATED: "PRODUCT_UPDATED",
  CATEGORY_CREATED: "CATEGORY_CREATED",
  CATEGORY_UPDATED: "CATEGORY_UPDATED",
};
